import type { ColorTheme } from "@/types";
const Base = {
  light: {
    background: "#",
    backgroundImage: {
      id: 0,
      value: "#0",
      type: "color | image",
      url: undefined,
    },
    backgroundAdditional: "#",
    primary: "#",
    disabledPrimary: "#",
    secondary: "#",
    text: "#",
    textAdditional: "#",
    textInPrimary: "",
    link: "#0000ff",
    border: "#",
    error: "#B9130F",
    notification: "",
    // calendar
    calendarBackground: "#",
    calendarEnableDayBorder: "#",
    calendarDisableDayBorder: "#",
    calendarDayLabels: "#",
    calendarDayDisabled: "#",
    // tabs
    tabBackground: "#",
    tabIcon: "#",
    tabIconSelected: "#",
    // input
    inputBackground: "#",
    inputBorder: "#",
    // Icon
    icon: "#",
    // diary
    card: "#",
    diaryNotesBackground: "#",
    aiCommentBackground: "#",
    questionBackground: "#",
    answerBackground: "#",
    // settings
    blockBackground: "#",
    // barStyle
    barStyle: "",
    // rich
    toolbarBackground: "#",
    toolbarIcon: "#",
  },
};

export const Colors: Record<string, ColorTheme> = {
  light: {
    // General
    background: "#8e8680",
    backgroundImage: {
      id: 201,
      value: "#8e8680",
      type: "image",
      url: require("@/assets/images//background/light.jpg"),
    },
    backgroundAdditional: "#bab0a9",
    primary: "#604d3f",
    disabledPrimary: "#a1958c",
    secondary: "#4a5365",
    text: "#1e140c",
    textAdditional: "#8e7868",
    textInPrimary: "#FFFFFF",
    link: "#0000ff",
    border: "#604d3f",
    error: "#B9130F",
    notification: "#ff5252",
    // calendar
    calendarBackground: "transparent",
    calendarEnableDayBorder: "#1e140c",
    calendarDisableDayBorder: "#c1aea0",
    calendarDayLabels: "#888",
    calendarDayDisabled: "#bfbfbf",

    // tabs
    tabBackground: "#FFFFFF",
    tabIcon: "#687076",
    tabIconSelected: "#604d3f",
    // input
    inputBackground: "#ffffff",
    inputBorder: "#a59285",
    // Icon
    icon: "#604d3f",
    // diary
    card: "#b5aea8",
    diaryNotesBackground: "#EFE7DA",
    aiCommentBackground: "#00000033",
    questionBackground: "transparent",
    answerBackground: "#00000033",
    //  settings
    blockBackground: "#b5aea8",
    // barStyle
    barStyle: "light",
    // rich
    toolbarBackground: "#8e8680",
    toolbarIcon: "#604d3f",
  },
  neonIce: {
    // General
    background: "#FFFFFF",
    backgroundImage: {
      id: 201,
      value: "#FFFFFF",
      type: "image",
      url: require("@/assets/images//background/neonIce.jpeg"),
    },
    backgroundAdditional: "#6ebbbd",

    primary: "#14E6ED",
    disabledPrimary: "#0c7578",
    secondary: "#0d888c",
    text: "#063739",
    textAdditional: "#687076",
    textInPrimary: "#FFFFFF",
    link: "#0000ff",
    border: "#E0E0E0",
    error: "#B9130F",
    notification: "#ff5252",
    // calendar
    calendarBackground: "transparent",
    calendarEnableDayBorder: "#5a5a5a",
    calendarDisableDayBorder: "#a6a6a6",
    calendarDayLabels: "#888",
    calendarDayDisabled: "#",

    // tabs
    tabBackground: "#FFFFFF",
    tabIcon: "#687076",
    tabIconSelected: "#14E6ED",
    // input
    inputBackground: "#ffffff",
    inputBorder: "#95d4d6",
    // Icon
    icon: "#14E6ED",
    // diary
    card: "#dcfbfb",
    diaryNotesBackground: "#EFE7DA",
    aiCommentBackground: "#ffffff33",
    questionBackground: "transparent",
    answerBackground: "#ffffff33",
    //  settings
    blockBackground: "#FFFFFF",
    // barStyle
    barStyle: "dark",
    // rich
    toolbarBackground: "#FFFFFF",
    toolbarIcon: "#344360",
  },
  avocado: {
    // General
    background: "#FFFFFF",
    backgroundImage: {
      id: 201,
      value: "#FFFFFF",
      type: "image",
      url: require("@/assets/images//background/avocado.jpeg"),
    },
    backgroundAdditional: "#badd9f",

    primary: "#839179",
    disabledPrimary: "#51594c",
    secondary: "#586151",
    text: "#30352c",
    textAdditional: "#6f7768",
    textInPrimary: "#FFFFFF",
    link: "#0000ff",
    border: "#E0E0E0",
    error: "#B9130F",
    notification: "#ff5252",
    // calendar
    calendarBackground: "transparent",
    calendarEnableDayBorder: "#5a5a5a",
    calendarDisableDayBorder: "#a6a6a6",
    calendarDayLabels: "#888",
    calendarDayDisabled: "#",

    // tabs
    tabBackground: "#FFFFFF",
    tabIcon: "#687076",
    tabIconSelected: "#839179",
    // input
    inputBackground: "#ffffff",
    inputBorder: "#7e837a",
    // Icon
    icon: "#839179",
    // diary
    card: "#e7f8db",
    diaryNotesBackground: "#EFE7DA",
    aiCommentBackground: "#ffffff33",
    questionBackground: "transparent",
    answerBackground: "#ffffff33",
    //  settings
    blockBackground: "#FFFFFF",
    // barStyle
    barStyle: "dark",
    // rich
    toolbarBackground: "#FFFFFF",
    toolbarIcon: "#344360",
  },
  heart: {
    // General
    background: "#FFFFFF",
    backgroundImage: {
      id: 201,
      value: "#FFFFFF",
      type: "image",
      url: require("@/assets/images//background/heart.jpg"),
    },
    backgroundAdditional: "#d86668",

    primary: "#DD0103",
    disabledPrimary: "#7e0405",
    secondary: "#0d888c",
    text: "#220101",
    textAdditional: "#687076",
    textInPrimary: "#FFFFFF",
    link: "#0000ff",
    border: "#E0E0E0",
    error: "#B9130F",
    notification: "#ff5252",
    // calendar
    calendarBackground: "transparent",
    calendarEnableDayBorder: "#5a5a5a",
    calendarDisableDayBorder: "#a6a6a6",
    calendarDayLabels: "#888",
    calendarDayDisabled: "#",

    // tabs
    tabBackground: "#FFFFFF",
    tabIcon: "#687076",
    tabIconSelected: "#DD0103",
    // input
    inputBackground: "#ffffff",
    inputBorder: "#a64647",
    // Icon
    icon: "#DD0103",
    // diary
    card: "#ecb8b8",
    diaryNotesBackground: "#EFE7DA",
    aiCommentBackground: "#ffffff33",
    questionBackground: "transparent",
    answerBackground: "#ffffff33",
    //  settings
    blockBackground: "#FFFFFF",
    // barStyle
    barStyle: "dark",
    // rich
    toolbarBackground: "#FFFFFF",
    toolbarIcon: "#344360",
  },
  space: {
    // General
    background: "#FFFFFF",
    backgroundImage: {
      id: 201,
      value: "#FFFFFF",
      type: "image",
      url: require("@/assets/images//background/space.jpg"),
    },
    backgroundAdditional: "#babfc8",

    primary: "#344360",
    disabledPrimary: "#272f3e",
    secondary: "#4a5365",
    text: "#2E3A59",
    textAdditional: "#687076",
    textInPrimary: "#FFFFFF",
    link: "#0000ff",
    border: "#E0E0E0",
    error: "#B9130F",
    notification: "#ff5252",
    // calendar
    calendarBackground: "transparent",
    calendarEnableDayBorder: "#f4f4f4",
    calendarDisableDayBorder: "#bfbdbd",
    calendarDayLabels: "#888",
    calendarDayDisabled: "#",

    // tabs
    tabBackground: "#FFFFFF",
    tabIcon: "#687076",
    tabIconSelected: "#344360",
    // input
    inputBackground: "#ffffff",
    inputBorder: "#6d788e",
    // Icon
    icon: "#344360",
    // diary
    card: "#c3d0dc",
    diaryNotesBackground: "#EFE7DA",
    aiCommentBackground: "#ffffff33",
    questionBackground: "transparent",
    answerBackground: "#ffffff33",
    //  settings
    blockBackground: "#FFFFFF",
    // barStyle
    barStyle: "dark",
    // rich
    toolbarBackground: "#FFFFFF",
    toolbarIcon: "#344360",
  },

  calmMind: {
    background: "#F6F7F9",
    backgroundImage: {
      id: 202,
      value: "#F6F7F9",
      type: "image",
      url: require("@/assets/images//background/calmMind.jpg"),
    },
    backgroundAdditional: "#cdd3df",
    primary: "#5BA9A6",
    disabledPrimary: "#4a7170",
    secondary: "#FFC97A",
    text: "#23272F",
    textAdditional: "#8899AA",
    textInPrimary: "#FFFFFF",
    link: "#5BA9A6",
    border: "#E5E7EB",
    error: "#FF7A7A",
    notification: "#ff5252",
    // calendar
    calendarBackground: "transparent",
    calendarEnableDayBorder: "#5BA9A6",
    calendarDisableDayBorder: "#E5E7EB",
    calendarDayLabels: "#888",
    calendarDayDisabled: "#",
    // tabs
    tabBackground: "#F6F7F9",
    tabIcon: "#85a6a5",
    tabIconSelected: "#5BA9A6",
    // input
    inputBackground: "#F0F2F6",
    inputBorder: "#94bdbb",
    // Icon
    icon: "#5BA9A6",
    // diary
    card: "#BED0DA",
    diaryNotesBackground: "#FFFBEA",
    aiCommentBackground: "#ffffff33",
    questionBackground: "transparent",
    answerBackground: "#ffffff33",
    //  settings
    blockBackground: "#FFFFFF",
    // barStyle
    barStyle: "dark",
    // rich
    toolbarBackground: "#F6F7F9",
    toolbarIcon: "#5BA9A6",
  },

  orange: {
    background: "#FFF9F4",
    backgroundImage: {
      id: 203,
      value: "#FFF9F4",
      type: "image",
      url: require("@/assets/images//background/orange.jpg"),
    },
    backgroundAdditional: "#dcd0c5",
    primary: "#FF8200",
    disabledPrimary: "#984f02",
    secondary: "#FFB354",
    text: "#2E2E2E",
    textAdditional: "#A86800",
    textInPrimary: "#FFF",
    link: "#FF8200",
    border: "#FFD09A",
    error: "#D7263D",
    notification: "#ff5252",
    // calendar
    calendarBackground: "transparent",
    calendarEnableDayBorder: "#FF8200",
    calendarDisableDayBorder: "#FFD09A",
    calendarDayLabels: "#888",
    calendarDayDisabled: "#",
    // tabs
    tabBackground: "#FFF9F4",
    tabIcon: "#FFB354",
    tabIconSelected: "#FF8200",
    // input
    inputBackground: "#FFF4E3",
    inputBorder: "#a5805a",
    // Icon
    icon: "#FF8200",
    // diary
    card: "#FFF1DB",
    diaryNotesBackground: "#FFE9D1",
    aiCommentBackground: "#ffffff33",
    questionBackground: "transparent",
    answerBackground: "#ffffff33",
    //  settings
    blockBackground: "#FFFFFF",
    // barStyle
    barStyle: "dark",
    // rich
    toolbarBackground: "#FFE4C7",
    toolbarIcon: "#FF8200",
  },

  sandDune: {
    // General
    background: "#8e8680",
    backgroundImage: {
      id: 205,
      value: "#8e8680",
      type: "image",
      url: require("@/assets/images//background/sandDune.jpg"),
    },
    backgroundAdditional: "#bab0a9",
    primary: "#604d3f",
    disabledPrimary: "#453b34",
    secondary: "#4a5365",
    text: "#344360",
    textAdditional: "#687076",
    textInPrimary: "#FFFFFF",
    link: "#0000ff",
    border: "#604d3f",
    error: "#B9130F",
    notification: "#ff5252",
    // calendar
    calendarBackground: "transparent",
    calendarEnableDayBorder: "#f4f4f4",
    calendarDisableDayBorder: "#bfbdbd",
    calendarDayLabels: "#888",
    calendarDayDisabled: "#",

    // tabs
    tabBackground: "#FFFFFF",
    tabIcon: "#687076",
    tabIconSelected: "#604d3f",
    // input
    inputBackground: "#ffffff",
    inputBorder: "#a59589",
    // Icon
    icon: "#604d3f",
    // diary
    card: "#b5aea8",
    diaryNotesBackground: "#EFE7DA",
    aiCommentBackground: "#00000033",
    questionBackground: "transparent",
    answerBackground: "#00000033",
    //  settings
    blockBackground: "#b5aea8",
    // barStyle
    barStyle: "light",
    // rich
    toolbarBackground: "#8e8680",
    toolbarIcon: "#604d3f",
  },

  yellowBokeh: {
    // General
    background: "#222020",
    backgroundImage: {
      id: 206,
      value: "#222020",
      type: "image",
      url: require("@/assets/images/background/yellowBokeh.jpg"),
    },
    backgroundAdditional: "#534f4f",
    primary: "#a59f37",
    disabledPrimary: "#6a6732",
    secondary: "#4a5365",
    text: "#b6bcca",
    textAdditional: "#687076",
    textInPrimary: "#FFFFFF",
    link: "#0000ff",
    border: "#E0E0E0",
    error: "#B9130F",
    notification: "#ff5252",
    // calendar
    calendarBackground: "transparent",
    calendarEnableDayBorder: "#f4f4f4",
    calendarDisableDayBorder: "#989696",
    calendarDayLabels: "#888",
    calendarDayDisabled: "#",
    // tabs
    tabBackground: "#222020",
    tabIcon: "#687076",
    tabIconSelected: "#a59f37",
    // input
    inputBackground: "#ffffff",
    inputBorder: "#716f4a",
    // Icon
    icon: "#a59f37",
    // diary
    card: "#494545",
    diaryNotesBackground: "#EFE7DA",
    aiCommentBackground: "#00000033",
    questionBackground: "transparent",
    answerBackground: "#00000033",
    //  settings
    blockBackground: "#222020",
    // barStyle
    barStyle: "light",
    // rich
    toolbarBackground: "#222020",
    toolbarIcon: "#a59f37",
  },

  ball: {
    // General
    background: "#222020",
    backgroundImage: {
      id: 206,
      value: "#222020",
      type: "image",
      url: require("@/assets/images/background/ball.jpeg"),
    },
    backgroundAdditional: "#534f4f",
    primary: "#202020",
    disabledPrimary: "#3e3e3e",
    secondary: "#4a5365",
    text: "#b6bcca",
    textAdditional: "#687076",
    textInPrimary: "#FFFFFF",
    link: "#0000ff",
    border: "#E0E0E0",
    error: "#B9130F",
    notification: "#ff5252",
    // calendar
    calendarBackground: "transparent",
    calendarEnableDayBorder: "#f4f4f4",
    calendarDisableDayBorder: "#989696",
    calendarDayLabels: "#888",
    calendarDayDisabled: "#",
    // tabs
    tabBackground: "#222020",
    tabIcon: "#687076",
    tabIconSelected: "#121212",
    // input
    inputBackground: "#ffffff",
    inputBorder: "#615858",
    // Icon
    icon: "#202020",
    // diary
    card: "#494545",
    diaryNotesBackground: "#EFE7DA",
    aiCommentBackground: "#00000033",
    questionBackground: "transparent",
    answerBackground: "#00000033",
    //  settings
    blockBackground: "#222020",
    // barStyle
    barStyle: "light",
    // rich
    toolbarBackground: "#222020",
    toolbarIcon: "#7e7d6f",
  },

  dark: {
    // General
    background: "#151718",
    backgroundImage: {
      id: 204,
      value: "#151718",
      type: "color",
    },
    backgroundAdditional: "#282c2e",
    primary: "#344360",
    disabledPrimary: "#2d3340",
    secondary: "",
    text: "#ECEDEE",
    textAdditional: "#a5a5a6",
    textInPrimary: "#FFFFFF",
    link: "#0000ff",
    border: "#2A2D2F",
    error: "#B9130F",
    notification: "#ff5252",
    // calendar
    calendarBackground: "transparent",
    calendarEnableDayBorder: "#5b6165",
    calendarDisableDayBorder: "#1e2022",
    calendarDayLabels: "#888",
    calendarDayDisabled: "#",
    // tabs
    tabBackground: "#151718",
    tabIcon: "#9BA1A6",
    tabIconSelected: "#344360",
    // input
    inputBackground: "#000000",
    inputBorder: "#73809a",
    // Icon
    icon: "#344360",
    // diary
    card: "#151718",
    diaryNotesBackground: "#4b5255",
    aiCommentBackground: "#00000033",
    questionBackground: "transparent",
    answerBackground: "#00000033",
    //  settings
    blockBackground: "#FFFFFF",
    // barStyle
    barStyle: "light",
    // rich
    toolbarBackground: "#151718",
    toolbarIcon: "#344360",
  },
};
