export enum CodeStatus {
  OK = "OK",
  INVALID_CODE = "INVALID_CODE",
  EXPIRED_CODE = "EXPIRED_CODE",
  ATTEMPTS_EXCEEDED = "ATTEMPTS_EXCEEDED",
  RATE_LIMITED = "RATE_LIMITED",
  COOLDOWN = "COOLDOWN",
  BAD = "BAD",
}
