export type ColorTheme = {
  // General
  background: string;
  backgroundAdditional: string;
  card: string;
  secondaryBackground: string;
  additionalBackground: string;
  primary: string;
  secondary: string;
  additional: string;
  text: string;
  textAdditional: string;
  textInPrimary: string;
  secondaryText: string;
  additionalText: string;
  link: string;
  border: string;
  calendarEnableDayBorder: string;
  calendarDisableDayBorder: string;
  error: string;
  // icon
  icon: string;
  tabIcon: string;
  tabIconDefault: string;
  tabIconSelected: string;
  // input
  inputBackground: string;
  inputBorder: string;
  // radio
  radioBackground: string;
  radioBorder: string;
  radioSelectedBorder: string;
  radioSelectedBackground: string;
  radioSelectedDot: string;
  // plans Modal
  tariff: string;
  tokens: string;
  // settings
  settingsBlockBackground: string;
  // diary
  diaryNotesBackground: string;
  aiCommentBackground: string;
  entryBackground: string;
  // calendar
  calendarBackground: string;
};
